import {
	TabPanelService,
	TAB_PRODUCT_DESCRIPTION,
	TAB_PRODUCT_NUM_ORDERS,
	TAB_PRODUCT_PRICE,
} from './TabPanelService'

export {
	TAB_PRODUCT_DESCRIPTION,
	TAB_PRODUCT_NUM_ORDERS,
	TAB_PRODUCT_PRICE,
	TabPanelService,
}
