import {
	PageError,
	PAGE_ERROR_CODE_NOT_FOUND,
	PAGE_ERROR_CODE_UNAUTHORIZED,
	PAGE_ERROR_CODE_NOT_A_SENSHI,
} from './PageError'

export {
	PageError,
	PAGE_ERROR_CODE_NOT_FOUND,
	PAGE_ERROR_CODE_UNAUTHORIZED,
	PAGE_ERROR_CODE_NOT_A_SENSHI,
}
