import { createBrowserHistory } from 'history'
const history = createBrowserHistory()

const ROUTE = 'route'
const ROUTE_TO = ROUTE + 'To'
const ROUTE_FROM = ROUTE + 'From'
const ROUTE_PATH = ROUTE + 'Path'
const ROUTE_ACCESSIBILITY = ROUTE + 'Guarded'
const ROUTE_ACCESSIBILITY_PRIVATE = ROUTE + 'Private'
const ROUTE_ACCESSIBILITY_PUBLIC = ROUTE + 'Public'
const ROUTE_ACCESSIBILITY_FREE = ROUTE + 'Free'
const ROUTE_PAGE_INDEX = '/index'
const ROUTE_PAGE_PROFILE = '/profile'
const ROUTE_PAGE_SIGN_UP = '/signUp'
const ROUTE_PAGE_SIGN_IN = '/signIn'
const ROUTE_PAGE_SETTINGS = '/settings'
const ROUTE_PAGE_NOTIFICATIONS = '/notifications'
const ROUTE_PAGE_404 = '/404'
const ROUTE_PARAM_SETTINGS = 'tabPane'
const ROUTE_SETTINGS_PARAM_GENERAL = 'general'
const ROUTE_SETTINGS_PARAM_PAYMENT = 'payment'
const ROUTE_SETTINGS_PARAM_ACCOUNT = 'account'
const ROUTE_SETTINGS_PARAM_NOTIFICATION = 'notification'
const ROUTE_PAGE_SETTINGS_COMMON = `${ROUTE_PAGE_SETTINGS}/:${ROUTE_PARAM_SETTINGS}(${ROUTE_SETTINGS_PARAM_GENERAL}|${ROUTE_SETTINGS_PARAM_PAYMENT}|${ROUTE_SETTINGS_PARAM_ACCOUNT}|${ROUTE_SETTINGS_PARAM_NOTIFICATION})`
const ROUTE_PAGE_SETTINGS_GENERAL = `${ROUTE_PAGE_SETTINGS}/${ROUTE_SETTINGS_PARAM_GENERAL}`
const ROUTE_PAGE_SETTINGS_PAYMENT = `${ROUTE_PAGE_SETTINGS}/${ROUTE_SETTINGS_PARAM_PAYMENT}`
const ROUTE_PAGE_SETTINGS_ACCOUNT = `${ROUTE_PAGE_SETTINGS}/${ROUTE_SETTINGS_PARAM_ACCOUNT}`
const ROUTE_PAGE_SETTINGS_NOTIFICATION = `${ROUTE_PAGE_SETTINGS}/${ROUTE_SETTINGS_PARAM_NOTIFICATION}`
const ROUTE_PAGE_PASSWORD_RESET = '/passwordReset'

export {
	ROUTE_TO,
	ROUTE_FROM,
	ROUTE_PATH,
	ROUTE_ACCESSIBILITY,
	ROUTE_ACCESSIBILITY_PRIVATE,
	ROUTE_ACCESSIBILITY_PUBLIC,
	ROUTE_ACCESSIBILITY_FREE,
	ROUTE_PAGE_INDEX,
	ROUTE_PAGE_PROFILE,
	ROUTE_PAGE_SIGN_UP,
	ROUTE_PAGE_SIGN_IN,
	ROUTE_PAGE_SETTINGS,
	ROUTE_PARAM_SETTINGS,
	ROUTE_PAGE_SETTINGS_COMMON,
	ROUTE_PAGE_SETTINGS_GENERAL,
	ROUTE_PAGE_SETTINGS_PAYMENT,
	ROUTE_PAGE_SETTINGS_ACCOUNT,
	ROUTE_PAGE_SETTINGS_NOTIFICATION,
	ROUTE_PAGE_PASSWORD_RESET,
	ROUTE_PAGE_404,
	ROUTE_PAGE_NOTIFICATIONS,
	history,
}
