const ROUTE = 'route'
const ROUTE_TO = ROUTE + 'To'
const ROUTE_FROM = ROUTE + 'From'
const ROUTE_PATH = ROUTE + 'Path'
const ROUTE_ACCESSIBILITY = ROUTE + 'Guarded'
const ROUTE_ACCESSIBILITY_PRIVATE = ROUTE + 'Private'
const ROUTE_ACCESSIBILITY_PUBLIC = ROUTE + 'Public'
const ROUTE_ACCESSIBILITY_FREE = ROUTE + 'Free'
const ROUTE_PAGE_INDEX = '/index'
const ROUTE_PAGE_PROFILE = '/profile'
const ROUTE_PAGE_SIGN_UP = '/signUp'
const ROUTE_PAGE_SIGN_IN = '/signIn'
const ROUTE_PAGE_SETTINGS = '/settings'
const ROUTE_PARAM_SETTINGS = 'tabPane'
const ROUTE_PARAM_SETTINGS_GENERAL = 'general'
const ROUTE_PARAM_SETTINGS_PAYMENT = 'payment'
const ROUTE_PARAM_SETTINGS_ACCOUNT = 'account'
const ROUTE_PARAM_SETTINGS_NOTIFICATION = 'notification'
const ROUTE_PAGE_SETTINGS_COMMON = `${ROUTE_PAGE_SETTINGS}/:${ROUTE_PARAM_SETTINGS}(${ROUTE_PARAM_SETTINGS_GENERAL}|${ROUTE_PARAM_SETTINGS_PAYMENT}|${ROUTE_PARAM_SETTINGS_ACCOUNT}|${ROUTE_PARAM_SETTINGS_NOTIFICATION})`
const ROUTE_PAGE_SETTINGS_GENERAL =
	ROUTE_PAGE_SETTINGS + '/' + ROUTE_PARAM_SETTINGS_GENERAL
const ROUTE_PAGE_SETTINGS_PAYMENT =
	ROUTE_PAGE_SETTINGS + '/' + ROUTE_PARAM_SETTINGS_PAYMENT
const ROUTE_PAGE_SETTINGS_ACCOUNT =
	ROUTE_PAGE_SETTINGS + '/' + ROUTE_PARAM_SETTINGS_ACCOUNT
const ROUTE_PAGE_SETTINGS_NOTIFICATION =
	ROUTE_PAGE_SETTINGS + '/' + ROUTE_PARAM_SETTINGS_NOTIFICATION
const ROUTE_PAGE_PASSWORD_RESET = '/passwordReset'

export {
	ROUTE_TO,
	ROUTE_FROM,
	ROUTE_PATH,
	ROUTE_ACCESSIBILITY,
	ROUTE_ACCESSIBILITY_PRIVATE,
	ROUTE_ACCESSIBILITY_PUBLIC,
	ROUTE_ACCESSIBILITY_FREE,
	ROUTE_PAGE_INDEX,
	ROUTE_PAGE_PROFILE,
	ROUTE_PAGE_SIGN_UP,
	ROUTE_PAGE_SIGN_IN,
	ROUTE_PAGE_SETTINGS,
	ROUTE_PARAM_SETTINGS,
	ROUTE_PAGE_SETTINGS_COMMON,
	ROUTE_PAGE_SETTINGS_GENERAL,
	ROUTE_PAGE_SETTINGS_PAYMENT,
	ROUTE_PAGE_SETTINGS_ACCOUNT,
	ROUTE_PAGE_SETTINGS_NOTIFICATION,
	ROUTE_PAGE_PASSWORD_RESET,
}
