// [ROUTE_PAGE]s
import {
	IndexPage,
	ProfilePage,
	SettingsPage,
	SignInPage,
	SignUpPage,
	PasswordResetPage,
} from 'views'

// constants
import {
	ROUTE_PAGE,
	ROUTE_PATH,
	ROUTE_ACCESSIBILITY,
	ROUTE_ACCESSIBILITY_PRIVATE,
	ROUTE_ACCESSIBILITY_PUBLIC,
	ROUTE_ACCESSIBILITY_FREE,
	ROUTE_PAGE_INDEX,
	ROUTE_PAGE_PROFILE,
	ROUTE_PAGE_SIGN_UP,
	ROUTE_PAGE_SIGN_IN,
	ROUTE_PAGE_SETTINGS,
	ROUTE_PAGE_PASSWORD_RESET,
} from 'constantValues'

const routes = [
	{
		[ROUTE_PAGE]: IndexPage,
		[ROUTE_PATH]: ROUTE_PAGE_INDEX,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_FREE,
	},
	{
		[ROUTE_PAGE]: ProfilePage,
		[ROUTE_PATH]: ROUTE_PAGE_PROFILE,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_PRIVATE,
	},
	{
		[ROUTE_PAGE]: SettingsPage,
		[ROUTE_PATH]: ROUTE_PAGE_SETTINGS,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_PRIVATE,
	},
	{
		[ROUTE_PAGE]: SignUpPage,
		[ROUTE_PATH]: ROUTE_PAGE_SIGN_UP,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_PUBLIC,
	},
	{
		[ROUTE_PAGE]: SignInPage,
		[ROUTE_PATH]: ROUTE_PAGE_SIGN_IN,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_PUBLIC,
	},
	{
		[ROUTE_PAGE]: PasswordResetPage,
		[ROUTE_PATH]: ROUTE_PAGE_PASSWORD_RESET,
		[ROUTE_ACCESSIBILITY]: ROUTE_ACCESSIBILITY_PUBLIC,
	},
]

export default routes
