const AUTH_MODAL = 'authModal'
const AUTH_MODAL_BODY = AUTH_MODAL + 'Body'
const AUTH_MODAL_OPEN = AUTH_MODAL + 'Open'
const AUTH_MODAL_TITLE = AUTH_MODAL + 'Title'
const AUTH_MODAL_LOADER = AUTH_MODAL + 'Loader'
const AUTH_MODAL_CALLBACK = AUTH_MODAL + 'Callback'

export {
	AUTH_MODAL,
	AUTH_MODAL_BODY,
	AUTH_MODAL_OPEN,
	AUTH_MODAL_TITLE,
	AUTH_MODAL_LOADER,
	AUTH_MODAL_CALLBACK,
}
