const VALID = 'Valid'
const SUBMITTING = 'Submitting'
const VALIDATION = 'Validation'
const EXTRA_HEIGHT = 'ExtraHeight'
const SUBMIT_ERRORS = 'SubmitErrors'

const EMAIL = 'email'
const EMAIL_VALID = EMAIL + VALID
const EMAIL_VALIDATION = EMAIL + VALIDATION
const EMAIL_EXTRA_HEIGHT = EMAIL + EXTRA_HEIGHT
const EMAIL_SUBMIT_ERRORS = EMAIL + SUBMIT_ERRORS

const PASSWORD = 'password'
const PASSWORD_VALID = PASSWORD + VALID
const PASSWORD_VALIDATION = PASSWORD + VALIDATION
const PASSWORD_EXTRA_HEIGHT = PASSWORD + EXTRA_HEIGHT
const PASSWORD_SUBMIT_ERRORS = PASSWORD + SUBMIT_ERRORS

const TERM = 'term'
const TERM_VALID = TERM + VALID
const TERM_VALIDATION = TERM + VALIDATION
const TERM_SUBMIT_ERRORS = TERM + SUBMIT_ERRORS

const USERNAME = 'username'
const USERNAME_VALID = USERNAME + VALID
const USERNAME_VALIDATION = USERNAME + VALIDATION
const USERNAME_SUBMIT_ERRORS = USERNAME + SUBMIT_ERRORS

const ON = 'on'
const SIGN_UP = 'SignUp'
const IS_USER_EXIST = 'IsUserExist'
const ON_IS_USER_EXIST = ON + IS_USER_EXIST
const ON_SIGN_UP = ON + SIGN_UP
const SIGNED_IN = 'succeed'

// TODO: gonna remove extra height feature someday

export {
	VALID,
	SUBMITTING,
	SUBMIT_ERRORS,
	EXTRA_HEIGHT,
	EMAIL,
	EMAIL_VALID,
	EMAIL_VALIDATION,
	EMAIL_EXTRA_HEIGHT,
	EMAIL_SUBMIT_ERRORS,
	PASSWORD,
	PASSWORD_VALID,
	PASSWORD_VALIDATION,
	PASSWORD_EXTRA_HEIGHT,
	PASSWORD_SUBMIT_ERRORS,
	TERM,
	TERM_VALID,
	TERM_VALIDATION,
	TERM_SUBMIT_ERRORS,
	USERNAME,
	USERNAME_VALID,
	USERNAME_VALIDATION,
	USERNAME_SUBMIT_ERRORS,
	ON_SIGN_UP,
	ON_IS_USER_EXIST,
	SIGNED_IN,
}
