const ON = 'On'
const IS = 'Is'
const VALID = 'Valid'
const EXIST = 'Exist'
const IS_VALID = IS + VALID
const SUBMITTING = 'Submitting'
const VALIDATION = 'Validation'
const EXTRA_HEIGHT = 'ExtraHeight'
const SUBMIT_ERRORS = 'SubmitErrors'

const EMAIL = 'email'
const EMAIL_IS_VALID = EMAIL + IS_VALID
const EMAIL_VALIDATION = EMAIL + VALIDATION
const EMAIL_EXTRA_HEIGHT = EMAIL + EXTRA_HEIGHT
const EMAIL_SUBMIT_ERRORS = EMAIL + SUBMIT_ERRORS

const PASSWORD = 'password'
const PASSWORD_IS_VALID = PASSWORD + IS_VALID
const PASSWORD_VALIDATION = PASSWORD + VALIDATION
const PASSWORD_EXTRA_HEIGHT = PASSWORD + EXTRA_HEIGHT
const PASSWORD_SUBMIT_ERRORS = PASSWORD + SUBMIT_ERRORS

const TERM = 'term'
const TERM_IS_VALID = TERM + IS_VALID
const TERM_VALIDATION = TERM + VALIDATION
const TERM_SUBMIT_ERRORS = TERM + SUBMIT_ERRORS

const DISPLAYNAME = 'displayName'
const DISPLAYNAME_IS_VALID = DISPLAYNAME + IS_VALID
const DISPLAYNAME_VALIDATION = DISPLAYNAME + VALIDATION
const DISPLAYNAME_EXTRA_HEIGHT = DISPLAYNAME + EXTRA_HEIGHT
const DISPLAYNAME_SUBMIT_ERRORS = DISPLAYNAME + SUBMIT_ERRORS

const SIGN_UP = 'SignUp'
const ON_SIGN_UP = ON + SIGN_UP
const SIGNED_IN = 'signed_in'
const IS_EMAIL_EXIST = IS + EMAIL + EXIST
const ON_IS_EMAIL_EXIST = ON + IS_EMAIL_EXIST

// TODO: gonna remove extra height feature someday

export {
	IS_VALID,
	SUBMITTING,
	SUBMIT_ERRORS,
	EXTRA_HEIGHT,
	EMAIL,
	EMAIL_IS_VALID,
	EMAIL_VALIDATION,
	EMAIL_EXTRA_HEIGHT,
	EMAIL_SUBMIT_ERRORS,
	PASSWORD,
	PASSWORD_IS_VALID,
	PASSWORD_VALIDATION,
	PASSWORD_EXTRA_HEIGHT,
	PASSWORD_SUBMIT_ERRORS,
	TERM,
	TERM_IS_VALID,
	TERM_VALIDATION,
	TERM_SUBMIT_ERRORS,
	DISPLAYNAME,
	DISPLAYNAME_IS_VALID,
	DISPLAYNAME_VALIDATION,
	DISPLAYNAME_EXTRA_HEIGHT,
	DISPLAYNAME_SUBMIT_ERRORS,
	ON_SIGN_UP,
	ON_IS_EMAIL_EXIST,
	SIGNED_IN,
}
