// TODO this should turn into npm library so that backend can use the same code
// constants is a nodejs module, so the folder is named constantValues instead

import {
	API_DATA,
	API_STATUS,
	API_CODE,
	API_MESSAGE,
	API_SIGN_UP,
	API_SIGN_UP_INPUT,
	API_SIGN_UP_EMAIL,
	API_SIGN_UP_PASSWORD,
	API_SIGN_UP_DISPLAY_NAME,
} from 'constantValues/ApiConstants'

import {
	ENV,
	ENV_PROJECT_ID,
	ENV_ENABLE_PLAYGROUND,
	ENV_APOLLO_ENGINE_API_KEY,
	ENV_CORS_WHITELIST,
} from 'constantValues/EnvKeyConstants'

import {
	INTERNAL_ERROR_CODE_1,
	INTERNAL_ERROR_CODE_2,
	INTERNAL_ERROR_CODE_3,
	INTERNAL_ERROR_CODE_4,
	INTERNAL_ERROR_CODE_5,
	INTERNAL_ERROR_CODE_6,
} from 'constantValues/InternalErrorConstants'

import {
	UNEXPECTED_ERROR_CODE_1,
	UNEXPECTED_ERROR_CODE_2,
	UNEXPECTED_ERROR_CODE_3,
	UNEXPECTED_ERROR_CODE_4,
	UNEXPECTED_ERROR_CODE_5,
	UNEXPECTED_ERROR_CODE_6,
	UNEXPECTED_ERROR_CODE_7,
} from 'constantValues/UnexpectedErrorConstants'

import { FIREBASE_STORAGE_USER_AVATAR } from 'constantValues/FirebaseConstants'

export {
	API_DATA,
	API_STATUS,
	API_CODE,
	API_MESSAGE,
	API_SIGN_UP,
	API_SIGN_UP_INPUT,
	API_SIGN_UP_EMAIL,
	API_SIGN_UP_PASSWORD,
	API_SIGN_UP_DISPLAY_NAME,
	ENV,
	ENV_PROJECT_ID,
	ENV_ENABLE_PLAYGROUND,
	ENV_APOLLO_ENGINE_API_KEY,
	ENV_CORS_WHITELIST,
	INTERNAL_ERROR_CODE_1,
	INTERNAL_ERROR_CODE_2,
	INTERNAL_ERROR_CODE_3,
	INTERNAL_ERROR_CODE_4,
	INTERNAL_ERROR_CODE_5,
	INTERNAL_ERROR_CODE_6,
	UNEXPECTED_ERROR_CODE_1,
	UNEXPECTED_ERROR_CODE_2,
	UNEXPECTED_ERROR_CODE_3,
	UNEXPECTED_ERROR_CODE_4,
	UNEXPECTED_ERROR_CODE_5,
	UNEXPECTED_ERROR_CODE_6,
	UNEXPECTED_ERROR_CODE_7,
	FIREBASE_STORAGE_USER_AVATAR,
}
