// TODO this should turn into npm library so that backend can use the same code
// constants is a nodejs module, so the folder is named constantValues instead

import {
	CODE,
	DATA,
	YEARS,
	STATUS,
	MESSAGE,
	ENDPOINT,
	MONTH_NAMES,
	MONTH_ABVS_SELECT,
	IS_VALID,
	EXTRA_HEIGHT,
	SUBMIT_ERRORS,
} from 'constantValues/CommonConstants'

import {
	ALERT_BODY,
	ALERT_COLOR,
	ALERT_OPEN,
} from 'constantValues/AlertConstants'

import {
	SIGN_UP,
	SIGN_UP_GQL_INPUT,
	SIGN_UP_EMAIL,
	SIGN_UP_EMAIL_EXTRA_HEIGHT,
	SIGN_UP_PASSWORD,
	SIGN_UP_PASSWORD_EXTRA_HEIGHT,
	SIGN_UP_USERNAME,
	SIGN_UP_USERNAME_EXTRA_HEIGHT,
} from 'constantValues/SignUpConstants'

import {
	ENV,
	ENV_PROJECT_ID,
	ENV_CORS_WHITELIST,
	ENV_ENABLE_PLAYGROUND,
	ENV_VERIFY_EMAIL_API_URL,
	ENV_APOLLO_ENGINE_API_KEY,
} from 'constantValues/EnvKeyConstants'

import {
	AUTH_MODAL,
	AUTH_MODAL_BODY,
	AUTH_MODAL_OPEN,
	AUTH_MODAL_TITLE,
	AUTH_MODAL_LOADER,
	AUTH_MODAL_CALLBACK,
} from 'constantValues/AuthModalConstants'

import {
	USER,
	USER_UID,
	USER_EMAIL,
	USER_GENDER,
	USER_COUNTRY,
	USER_LANGUAGES,
	USER_PHOTO_URL,
	USER_SIGNED_IN,
	USER_BIRTH_DATE,
	USER_DISPLAY_NAME,
	USER_PHONE_NUMBER,
	USER_PROVIDER_DATA,
	USER_EMAIL_IS_VERIFIED,
} from 'constantValues/UserConstants'

import {
	SIGN_IN_EMAIL,
	SIGN_IN_OPEN,
	SIGN_IN_CALLBACK,
} from 'constantValues/SignInConstants'

import {
	CARD_CVC,
	CARD_TYPE,
	CARD_CARDS,
	CARD_NUMBER,
	CARD_IS_OPEN,
	CARD_IS_DEFAULT,
	CARD_EXPIRY_YEAR,
	CARD_HOLDER_NAME,
	CARD_EXPIRY_MONTH,
	CARD_LAST_4_DIGITS,
} from 'constantValues/CardConstants'

import {
	INTERNAL_ERROR_CODE_1,
	INTERNAL_ERROR_CODE_2,
} from 'constantValues/InternalErrorConstants'

export {
	CODE,
	DATA,
	YEARS,
	STATUS,
	MESSAGE,
	ENDPOINT,
	MONTH_NAMES,
	MONTH_ABVS_SELECT,
	IS_VALID,
	EXTRA_HEIGHT,
	SUBMIT_ERRORS,
	ALERT_BODY,
	ALERT_COLOR,
	ALERT_OPEN,
	SIGN_UP,
	SIGN_UP_GQL_INPUT,
	SIGN_UP_EMAIL,
	SIGN_UP_EMAIL_EXTRA_HEIGHT,
	SIGN_UP_PASSWORD,
	SIGN_UP_PASSWORD_EXTRA_HEIGHT,
	SIGN_UP_USERNAME,
	SIGN_UP_USERNAME_EXTRA_HEIGHT,
	ENV,
	ENV_PROJECT_ID,
	ENV_CORS_WHITELIST,
	ENV_ENABLE_PLAYGROUND,
	ENV_VERIFY_EMAIL_API_URL,
	ENV_APOLLO_ENGINE_API_KEY,
	AUTH_MODAL,
	AUTH_MODAL_BODY,
	AUTH_MODAL_OPEN,
	AUTH_MODAL_TITLE,
	AUTH_MODAL_LOADER,
	AUTH_MODAL_CALLBACK,
	USER,
	USER_UID,
	USER_EMAIL,
	USER_GENDER,
	USER_COUNTRY,
	USER_LANGUAGES,
	USER_PHOTO_URL,
	USER_SIGNED_IN,
	USER_BIRTH_DATE,
	USER_DISPLAY_NAME,
	USER_PHONE_NUMBER,
	USER_PROVIDER_DATA,
	USER_EMAIL_IS_VERIFIED,
	SIGN_IN_EMAIL,
	SIGN_IN_OPEN,
	SIGN_IN_CALLBACK,
	CARD_CVC,
	CARD_TYPE,
	CARD_CARDS,
	CARD_NUMBER,
	CARD_IS_OPEN,
	CARD_IS_DEFAULT,
	CARD_EXPIRY_YEAR,
	CARD_HOLDER_NAME,
	CARD_EXPIRY_MONTH,
	CARD_LAST_4_DIGITS,
	INTERNAL_ERROR_CODE_1,
	INTERNAL_ERROR_CODE_2,
}
