const MODAL = 'Modal'
const AUTH_MODAL_BODY = MODAL + 'Body'
const AUTH_MODAL_OPEN = MODAL + 'Open'
const AUTH_MODAL_TITLE = MODAL + 'Title'
const AUTH_MODAL_LOADER = MODAL + 'Loader'
const AUTH_MODAL_CALLBACK = MODAL + 'Callback'

export {
	AUTH_MODAL_BODY,
	AUTH_MODAL_OPEN,
	AUTH_MODAL_TITLE,
	AUTH_MODAL_LOADER,
	AUTH_MODAL_CALLBACK,
}
