const ROUTE_PAGE_INDEX = '/index'
const ROUTE_PAGE_PROFILE = '/profile'
const ROUTE_PAGE_SIGN_UP = '/signUp'
const ROUTE_PAGE_SIGN_IN = '/signIn'
const ROUTE_PAGE_SETTINGS = '/settings'
const ROUTE_PAGE_SETTINGS_GENERAL = ROUTE_PAGE_SETTINGS + '/general'
const ROUTE_PAGE_SETTINGS_BILLING = ROUTE_PAGE_SETTINGS + '/billing'
const ROUTE_PAGE_SETTINGS_ACCOUNT = ROUTE_PAGE_SETTINGS + '/account'
const ROUTE_PAGE_SETTINGS_NOTIFICATION = ROUTE_PAGE_SETTINGS + '/notification'
const ROUTE_PAGE_PASSWORD_RESET = '/passwordReset'

export {
	ROUTE_PAGE_INDEX,
	ROUTE_PAGE_PROFILE,
	ROUTE_PAGE_SIGN_UP,
	ROUTE_PAGE_SIGN_IN,
	ROUTE_PAGE_SETTINGS,
	ROUTE_PAGE_SETTINGS_GENERAL,
	ROUTE_PAGE_SETTINGS_BILLING,
	ROUTE_PAGE_SETTINGS_ACCOUNT,
	ROUTE_PAGE_SETTINGS_NOTIFICATION,
	ROUTE_PAGE_PASSWORD_RESET,
}
