import {
	StoreUser,
	STORE_USER_STATE_BIRTH_DATE,
	STORE_USER_STATE_LANGUAGES,
	STORE_USER_STATE_SIGNED_IN,
	STORE_USER_STATE_GENDER,
	STORE_USER_STATE_AVATAR_URL,
	STORE_USER_STATE_DISPLAY_NAME,
	STORE_USER_STATE_UID,
	STORE_USER_STATE_EMAIL,
	STORE_USER_STATE_COUNTRY,
	STORE_USER_STATE_PHONE_NUMBER,
	STORE_USER_STATE_PROVIDER_DATA,
	STORE_USER_STATE_EMAIL_VERIFIED,
	STORE_USER_STATE_SIGNING_IN,
	STORE_USER_STATE_SOFT_SIGNED_IN,
	SET_STATE,
	RESET_STATE,
	SET_SIGNING_IN,
	INITIALIZE,
	RESET_AVATAR,
	ON_SIGN_IN,
	ON_SIGN_OUT,
} from 'state/User/StoreUser'

const storeUser = new StoreUser()
const storeUserSetState = storeUser[SET_STATE]
const storeUserResetState = storeUser[RESET_STATE]
const storeUserSetSigningIn = storeUser[SET_SIGNING_IN]
const storeUserInitialize = storeUser[INITIALIZE]
const storeUserResetAvatar = storeUser[RESET_AVATAR]
const storeUserOnSignIn = storeUser[ON_SIGN_IN]
const storeUserOnSignOut = storeUser[ON_SIGN_OUT]

export {
	storeUser,
	storeUserSetState,
	storeUserResetState,
	storeUserSetSigningIn,
	storeUserInitialize,
	storeUserResetAvatar,
	storeUserOnSignIn,
	storeUserOnSignOut,
	STORE_USER_STATE_BIRTH_DATE,
	STORE_USER_STATE_LANGUAGES,
	STORE_USER_STATE_SIGNED_IN,
	STORE_USER_STATE_GENDER,
	STORE_USER_STATE_AVATAR_URL,
	STORE_USER_STATE_DISPLAY_NAME,
	STORE_USER_STATE_UID,
	STORE_USER_STATE_EMAIL,
	STORE_USER_STATE_COUNTRY,
	STORE_USER_STATE_PHONE_NUMBER,
	STORE_USER_STATE_PROVIDER_DATA,
	STORE_USER_STATE_EMAIL_VERIFIED,
	STORE_USER_STATE_SIGNING_IN,
	STORE_USER_STATE_SOFT_SIGNED_IN,
}
