import { BODY, NAME, SECTION, CHECKBOXES, TITLE } from './TabPaneSettingList'

import {
	FIRESTORE_SETTINGS_NOTIFICATION_EMAIL,
	FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES,
	FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER,
	FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_CHATS,
	FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_COMMENTS,
	FIRESTORE_SETTINGS_NOTIFICATION_PUSH,
	FIRESTORE_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES,
	FIRESTORE_SETTINGS_NOTIFICATION_PUSH_CHATS,
	FIRESTORE_SETTINGS_NOTIFICATION_PUSH_COMMENTS,
} from 'constantValues'

const settingListNotification = () => [
	{
		[SECTION]: FIRESTORE_SETTINGS_NOTIFICATION_PUSH,
		[TITLE]: 'Push Notification',
		[CHECKBOXES]: [
			{
				[BODY]: 'Order Updates',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES,
			},
			{
				[BODY]: 'Chats',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_PUSH_CHATS,
			},
			{
				[BODY]: 'Comments',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_PUSH_COMMENTS,
			},
		],
	},
	{
		[SECTION]: FIRESTORE_SETTINGS_NOTIFICATION_EMAIL,
		[TITLE]: 'Email Notification',
		[CHECKBOXES]: [
			{
				[BODY]: 'Order Updates',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES,
			},
			{
				[BODY]: 'Newsletter',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER,
			},
			{
				[BODY]: 'Chats',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_CHATS,
			},
			{
				[BODY]: 'Comments',
				[NAME]: FIRESTORE_SETTINGS_NOTIFICATION_EMAIL_COMMENTS,
			},
		],
	},
]

export { settingListNotification }
