import {
	BUTTONS_COMMON_IMAGE_ID,
	BUTTONS_COMMON_IMAGE_TEXT,
	BUTTONS_COMMON_IMAGE_ICON,
} from './ButtonsImage'

import { createGetOptions } from '1_utils'

import {
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE,
} from '0_constants'

const options = [
	{
		[BUTTONS_COMMON_IMAGE_ID]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2,
		[BUTTONS_COMMON_IMAGE_TEXT]: 'Dota 2',
		[BUTTONS_COMMON_IMAGE_ICON]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2,
	},
	{
		[BUTTONS_COMMON_IMAGE_ID]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG,
		[BUTTONS_COMMON_IMAGE_TEXT]: 'PUBG',
		[BUTTONS_COMMON_IMAGE_ICON]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG,
	},
	{
		[BUTTONS_COMMON_IMAGE_ID]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL,
		[BUTTONS_COMMON_IMAGE_TEXT]: 'LOL',
		[BUTTONS_COMMON_IMAGE_ICON]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL,
	},
	{
		[BUTTONS_COMMON_IMAGE_ID]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX,
		[BUTTONS_COMMON_IMAGE_TEXT]: 'Apex',
		[BUTTONS_COMMON_IMAGE_ICON]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX,
	},
	{
		[BUTTONS_COMMON_IMAGE_ID]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE,
		[BUTTONS_COMMON_IMAGE_TEXT]: 'Fortnite',
		[BUTTONS_COMMON_IMAGE_ICON]: FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE,
	},
]

const buttonsIndex = [
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE,
]

const getButtonsImage = createGetOptions(options, BUTTONS_COMMON_IMAGE_ID)

export { buttonsIndex, getButtonsImage }
