// in future this should turn into npm library so that backend can use the same code
const EMAIL = 'email'
const PASSWORD = 'password'
const TERM = 'term'
const VALID = 'Valid'
const EMAIL_VALID = EMAIL + VALID
const PASSWORD_VALID = PASSWORD + VALID
const TERM_VALID = TERM + VALID
const EXTRA_HEIGHT = 'ExtraHeight'
const EMAIL_EXTRA_HEIGHT = EMAIL + EXTRA_HEIGHT
const PASSWORD_EXTRA_HEIGHT = PASSWORD + EXTRA_HEIGHT
const SUBMITTING = 'Submitting'
const SUBMIT_ERRORS = 'SubmitErrors'
const EMAIL_SUBMIT_ERRORS = EMAIL + SUBMIT_ERRORS
const PASSWORD_SUBMIT_ERRORS = PASSWORD + SUBMIT_ERRORS
const TERM_SUBMIT_ERRORS = TERM + SUBMIT_ERRORS
const VALIDATION = 'Validation'
const EMAIL_VALIDATION = EMAIL + VALIDATION
const PASSWORD_VALIDATION = PASSWORD + VALIDATION
const TERM_VALIDATION = TERM + VALIDATION
const ON = 'on'
const IS_USER_EXIST = 'IsUserExist'
const SIGN_UP = 'SignUp'
const ON_SIGN_UP = ON + SIGN_UP
const ON_IS_USER_EXIST = ON + IS_USER_EXIST

export {
	EMAIL,
	PASSWORD,
	TERM,
	VALID,
	EMAIL_VALID,
	PASSWORD_VALID,
	TERM_VALID,
	EXTRA_HEIGHT,
	EMAIL_EXTRA_HEIGHT,
	PASSWORD_EXTRA_HEIGHT,
	SUBMITTING,
	SUBMIT_ERRORS,
	EMAIL_SUBMIT_ERRORS,
	PASSWORD_SUBMIT_ERRORS,
	TERM_SUBMIT_ERRORS,
	EMAIL_VALIDATION,
	PASSWORD_VALIDATION,
	TERM_VALIDATION,
	ON_SIGN_UP,
	ON_IS_USER_EXIST,
}
