const FUNCTION_DATA = 'data'
const FUNCTION_STATUS = 'status'
const FUNCTION_CODE = 'code'
const FUNCTION_MESSAGE = 'message'
const FUNCTION_INPUT = 'Input'
const FUNCTION_EMAIL = 'email'
const FUNCTION_PASSWORD = 'password'
const FUNCTION_DISPLAY_NAME = 'displayName'
const FUNCTION_OAUTH_CODE = 'oauthCode'
const FUNCTION_OAUTH_TOKEN = 'oauthToken'
const FUNCTION_REDIRECT_URI = 'redirectUri'

const FUNCTION_SIGN_UP = 'signUp'
const FUNCTION_SIGN_UP_TWITCH = FUNCTION_SIGN_UP + 'Twitch'

export {
	FUNCTION_DATA,
	FUNCTION_STATUS,
	FUNCTION_CODE,
	FUNCTION_MESSAGE,
	FUNCTION_SIGN_UP,
	FUNCTION_INPUT,
	FUNCTION_EMAIL,
	FUNCTION_PASSWORD,
	FUNCTION_DISPLAY_NAME,
	FUNCTION_SIGN_UP_TWITCH,
	FUNCTION_OAUTH_CODE,
	FUNCTION_OAUTH_TOKEN,
	FUNCTION_REDIRECT_URI,
}
