const ROUTE_INDEX = '/index'
const ROUTE_PROFILE = '/profile'
const ROUTE_SIGN_UP = '/signUp'
const ROUTE_SIGN_IN = '/signIn'
const ROUTE_SETTINGS = '/settings'
const ROUTE_SETTINGS_GENERAL = ROUTE_SETTINGS + '/general'
const ROUTE_SETTINGS_BILLING = ROUTE_SETTINGS + '/billing'
const ROUTE_SETTINGS_ACCOUNT = ROUTE_SETTINGS + '/account'
const ROUTE_SETTINGS_NOTIFICATION = ROUTE_SETTINGS + '/notification'
const ROUTE_PASSWORD_RESET = '/passwordReset'

export {
	ROUTE_INDEX,
	ROUTE_PROFILE,
	ROUTE_SIGN_UP,
	ROUTE_SIGN_IN,
	ROUTE_SETTINGS,
	ROUTE_SETTINGS_GENERAL,
	ROUTE_SETTINGS_BILLING,
	ROUTE_SETTINGS_ACCOUNT,
	ROUTE_SETTINGS_NOTIFICATION,
	ROUTE_PASSWORD_RESET,
}
