import { OPEN, MODAL, EMAIL, CALLBACK } from 'constantValues/CommonConstants'

const SIGN_IN = 'socialSignUp'
const SIGN_IN_MODAL = SIGN_IN + MODAL
const SIGN_IN_MODAL_EMAIL = SIGN_IN_MODAL + EMAIL
const SIGN_IN_MODAL_OPEN = SIGN_IN_MODAL + OPEN
const SIGN_IN_MODAL_CALLBACK = SIGN_IN_MODAL + CALLBACK

export { SIGN_IN_MODAL_EMAIL, SIGN_IN_MODAL_OPEN, SIGN_IN_MODAL_CALLBACK }
