import { OPEN, TITLE, MODAL, BODY } from 'constantValues/CommonConstants'

const SOCIAL_AUTH = 'socialSignUp'
const SOCIAL_AUTH_MODAL = SOCIAL_AUTH + MODAL
const SOCIAL_AUTH_MODAL_BODY = SOCIAL_AUTH_MODAL + BODY
const SOCIAL_AUTH_MODAL_OPEN = SOCIAL_AUTH_MODAL + OPEN
const SOCIAL_AUTH_MODAL_TITLE = SOCIAL_AUTH_MODAL + TITLE
const SOCIAL_AUTH_MODAL_LOADER = SOCIAL_AUTH_MODAL + 'Loader'
const SOCIAL_AUTH_MODAL_CALLBACK = SOCIAL_AUTH_MODAL + 'CallBack'

export {
	SOCIAL_AUTH_MODAL_BODY,
	SOCIAL_AUTH_MODAL_OPEN,
	SOCIAL_AUTH_MODAL_TITLE,
	SOCIAL_AUTH_MODAL_LOADER,
	SOCIAL_AUTH_MODAL_CALLBACK,
}
