import { OPEN, TITLE, MODAL } from 'constantValues/commonConstants'

const SOCIAL_SIGN_UP = 'socialSignUp'
const SOCIAL_SIGN_UP_MODAL = SOCIAL_SIGN_UP + MODAL
const PROVIDER = 'Provider'
const SOCIAL_SIGN_UP_MODAL_PROVIDER_1 = SOCIAL_SIGN_UP_MODAL + PROVIDER + 1
const SOCIAL_SIGN_UP_MODAL_PROVIDER_2 = SOCIAL_SIGN_UP_MODAL + PROVIDER + 2
const SOCIAL_SIGN_UP_MODAL_OPEN = SOCIAL_SIGN_UP_MODAL + OPEN
const SOCIAL_SIGN_UP_MODAL_TITLE = SOCIAL_SIGN_UP_MODAL + TITLE
const SOCIAL_SIGN_UP_MODAL_CALLBACK = SOCIAL_SIGN_UP_MODAL + 'CallBack'

export {
	SOCIAL_SIGN_UP_MODAL_OPEN,
	SOCIAL_SIGN_UP_MODAL_TITLE,
	SOCIAL_SIGN_UP_MODAL_CALLBACK,
	SOCIAL_SIGN_UP_MODAL_PROVIDER_1,
	SOCIAL_SIGN_UP_MODAL_PROVIDER_2,
}
