const UNEXPECTED_ERROR_CODE_1 = [1, 'Password Reset-able Error']
const UNEXPECTED_ERROR_CODE_2 = [2, 'Email Not Exist Error']
const UNEXPECTED_ERROR_CODE_3 = [3, 'Password Reset Error']
const UNEXPECTED_ERROR_CODE_4 = [4, 'Email Sign In Error']
const UNEXPECTED_ERROR_CODE_5 = [5, 'Create User with Email Error']
const UNEXPECTED_ERROR_CODE_6 = [6, 'Get Redirect Result Error']
const UNEXPECTED_ERROR_CODE_7 = [7, 'Set User Initial General Setting Error']
const UNEXPECTED_ERROR_CODE_8 = [8, 'Social Link Error']
const UNEXPECTED_ERROR_CODE_9 = [9, 'Fetch Custom Token Error']
const UNEXPECTED_ERROR_CODE_10 = [10, 'Custom Token Sign In Error']
const UNEXPECTED_ERROR_CODE_11 = [11, 'Fetch Sign In Methods For Email Error']
const UNEXPECTED_ERROR_CODE_12 = [12, '']
const UNEXPECTED_ERROR_CODE_13 = [13, '']
const UNEXPECTED_ERROR_CODE_14 = [14, 'Something is Wrong, Please Try Again!']
const UNEXPECTED_ERROR_CODE_15 = [15, '']
export {
	UNEXPECTED_ERROR_CODE_1,
	UNEXPECTED_ERROR_CODE_2,
	UNEXPECTED_ERROR_CODE_3,
	UNEXPECTED_ERROR_CODE_4,
	UNEXPECTED_ERROR_CODE_5,
	UNEXPECTED_ERROR_CODE_6,
	UNEXPECTED_ERROR_CODE_7,
	UNEXPECTED_ERROR_CODE_8,
	UNEXPECTED_ERROR_CODE_9,
	UNEXPECTED_ERROR_CODE_10,
	UNEXPECTED_ERROR_CODE_11,
	UNEXPECTED_ERROR_CODE_12,
	UNEXPECTED_ERROR_CODE_13,
	UNEXPECTED_ERROR_CODE_14,
	UNEXPECTED_ERROR_CODE_15,
}
