import React from 'react'
import {
	DROP_DOWN_MENU_PROPS_TO,
	DROP_DOWN_MENU_PROPS_BODY,
	DROP_DOWN_MENU_PROPS_DIVIDER,
} from 'componentAtoms/DropdownMenu/DropdownMenu'
import {
	ROUTE_PAGE_SETTINGS_GENERAL,
	ROUTE_PAGE_HELP,
	ROUTE_PAGE_APPOINTMENTS,
} from 'routes'
import { storeUser, STATE, STORE_USER_STATE_USERNAME } from 'state'

const NavbarIndexItems = [
	{
		[DROP_DOWN_MENU_PROPS_TO]: ROUTE_PAGE_SETTINGS_GENERAL,
		[DROP_DOWN_MENU_PROPS_BODY]: (
			<strong>{storeUser[STATE][STORE_USER_STATE_USERNAME]}</strong>
		),
		[DROP_DOWN_MENU_PROPS_DIVIDER]: true,
	},
	{
		[DROP_DOWN_MENU_PROPS_TO]: ROUTE_PAGE_APPOINTMENTS,
		[DROP_DOWN_MENU_PROPS_BODY]: 'My Appointments',
		[DROP_DOWN_MENU_PROPS_DIVIDER]: true,
	},
	{
		[DROP_DOWN_MENU_PROPS_TO]: ROUTE_PAGE_SETTINGS_GENERAL,
		[DROP_DOWN_MENU_PROPS_BODY]: 'Settings',
		[DROP_DOWN_MENU_PROPS_DIVIDER]: false,
	},
	{
		[DROP_DOWN_MENU_PROPS_TO]: ROUTE_PAGE_HELP,
		[DROP_DOWN_MENU_PROPS_BODY]: 'Help',
		[DROP_DOWN_MENU_PROPS_DIVIDER]: false,
	},
	{
		[DROP_DOWN_MENU_PROPS_TO]: location => location,
		[DROP_DOWN_MENU_PROPS_BODY]: 'Sign Out',
		[DROP_DOWN_MENU_PROPS_DIVIDER]: false,
	},
]

export { NavbarIndexItems }
