const EMAIL = 'email'
const PASSWORD = 'password'
const TERM = 'term'
const VALID = 'Valid'
const EMAIL_VALID = EMAIL + VALID
const PASSWORD_VALID = PASSWORD + VALID
const TERM_VALID = TERM + VALID
const EXTRA_HEIGHT = 'ExtraHeight'
const EMAIL_EXTRA_HEIGHT = EMAIL + EXTRA_HEIGHT
const PASSWORD_EXTRA_HEIGHT = PASSWORD + EXTRA_HEIGHT
const SUBMITTING = 'Submitting'

export {
	EMAIL,
	PASSWORD,
	TERM,
	VALID,
	EMAIL_VALID,
	PASSWORD_VALID,
	TERM_VALID,
	EXTRA_HEIGHT,
	EMAIL_EXTRA_HEIGHT,
	PASSWORD_EXTRA_HEIGHT,
	SUBMITTING,
}
