import {
	resObj,
	signUpResObj,
	simplerResponseHandling,
	simplerErrorMessage,
	API_STATUS,
	API_CODE,
	API_MESSAGE,
	API_DATA,
} from 'utils/objects'
import { stopUndefined } from 'utils/codeToolings'

import {
	signUpEmailValidation,
	signUpPasswordValidation,
	checkBoxValidation,
	signUpUsernameValidation,
	signInEmailValidation,
	signInPasswordValidation,
	emailPopoverMessages,
	usernamePopoverMessages,
	passwordPopoverMessages,
	cardNumberValidation,
	cardNameValidation,
	cardCvcValidation,
	cardExpiryValidation,
	usernameLength,
} from 'utils/validation'

export {
	resObj,
	simplerResponseHandling,
	simplerErrorMessage,
	API_STATUS,
	API_CODE,
	API_MESSAGE,
	API_DATA,
	signUpResObj,
	stopUndefined,
	signUpEmailValidation,
	signUpPasswordValidation,
	checkBoxValidation,
	signUpUsernameValidation,
	signInEmailValidation,
	signInPasswordValidation,
	emailPopoverMessages,
	usernamePopoverMessages,
	passwordPopoverMessages,
	cardNumberValidation,
	cardNameValidation,
	cardCvcValidation,
	cardExpiryValidation,
	usernameLength,
}
