const FUNCTION_DATA = 'data'
const FUNCTION_STATUS = 'status'
const FUNCTION_CODE = 'code'
const FUNCTION_MESSAGE = 'message'
const FUNCTION_INPUT = 'Input'
const FUNCTION_EMAIL = 'email'
const FUNCTION_PASSWORD = 'password'
const FUNCTION_DISPLAY_NAME = 'displayName'
const FUNCTION_OAUTH_CODE = 'oauthCode'
const FUNCTION_TOKEN_CUSTOM = 'customToken'
const FUNCTION_REDIRECT_URI = 'redirectUri'
const FUNCTION_ON_SEED_DATA = 'onSeedData'
const FUNCTION_ON_TWITCH_SIGN_IN = 'signInTwitch'

export {
	FUNCTION_DATA,
	FUNCTION_STATUS,
	FUNCTION_CODE,
	FUNCTION_MESSAGE,
	FUNCTION_INPUT,
	FUNCTION_EMAIL,
	FUNCTION_PASSWORD,
	FUNCTION_DISPLAY_NAME,
	FUNCTION_OAUTH_CODE,
	FUNCTION_TOKEN_CUSTOM,
	FUNCTION_REDIRECT_URI,
	FUNCTION_ON_SEED_DATA,
	FUNCTION_ON_TWITCH_SIGN_IN,
}
