import uuidV4 from 'uuid/v4'

const STORAGE_USER_AVATAR = 'userAvatar'

const storagePathUserAvatar = uid => {
	return `${STORAGE_USER_AVATAR}/${uid}.jpg`
}

const CREATED_AT = 'createdAt'
const UPDATED_AT = 'updatedAt'

const FIRESTORE_USER = 'users'
const FIRESTORE_SELLER = 'senshi'
const FIRESTORE_USER_SETTINGS = 'settings'

const fireStorePathUserSettingsNotification = uid =>
	`${FIRESTORE_USER}/${uid}/${FIRESTORE_USER_SETTINGS}/notifications`

const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL = 'email'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES = 'orderUpdates'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER = 'newsletter'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_CHATS = 'chats'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_COMMENTS = 'comments'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH = 'push'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES = 'orderUpdates'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_CHATS = 'chats'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_COMMENTS = 'comments'

const FIRESTORE_USER_SELLER_FAVOURITE = 'favourite'

const fireStorePathUser_Seller = (uid, sellerUid) => {
	return `${FIRESTORE_USER}/${uid}/${FIRESTORE_SELLER}/${sellerUid}`
}

const firestorePathSettingsGeneral = uid => {
	return `${FIRESTORE_USER}/${uid}/${FIRESTORE_USER_SETTINGS}/general`
}

const FIRESTORE_USER_SETTINGS_GENERAL_DISPLAY_NAME = 'displayName'
const FIRESTORE_USER_SETTINGS_GENERAL_LANGUAGES = 'languages'
const FIRESTORE_USER_SETTINGS_GENERAL_USER_AVATAR = STORAGE_USER_AVATAR

const STORAGE_SELLER_AVATAR = STORAGE_USER_AVATAR
const STORAGE_SELLER_CAROUSEL = 'sellerCarousel'

const storagePathSellerAvatar = storagePathUserAvatar

const storagePathSellerCarousel = (uid, name = uuidV4()) => {
	return `${STORAGE_SELLER_CAROUSEL}/${uid}/${name}.jpg`
}

const fireStorePathSellerSettingProfile = uid => {
	return `${FIRESTORE_SELLER}/${uid}/${FIRESTORE_USER_SETTINGS}/profile`
}

const DATABASE_STATUS_ONLINE = 'online'
const DATABASE_STATUS_ONLINE_LAST = 'onlineLast'

const FIRESTORE_SELLER_SETTINGS_PROFILE_AVATAR = STORAGE_SELLER_AVATAR

const FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER = 'gender'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER_FEMALE = 'female'

const FIRESTORE_SELLER_SETTINGS_PROFILE_DISPLAY_NAME = FIRESTORE_USER_SETTINGS_GENERAL_DISPLAY_NAME

const FIRESTORE_SELLER_SETTINGS_PROFILE_VERIFIED = 'true'

const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS = 'channels'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_FACEBOOK = 'facebook'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_TWITCH = 'twitch'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_YOUTUBE = 'youtube'

const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES = 'services'

const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2 = 'Dota2'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG = 'PUBG'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL = 'LOL'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX = 'Apex'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE = 'Fortnite'

const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PRICE = 'price'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DESCR = 'description'
const FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_ORDERS = 'orders'

const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL = 'carousel'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_IMAGE = 'image'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_YOUTUBE = 'youtube'

export {
	CREATED_AT,
	UPDATED_AT,
	storagePathUserAvatar,
	STORAGE_USER_AVATAR,
	FIRESTORE_USER,
	FIRESTORE_USER_SETTINGS,
	fireStorePathUserSettingsNotification,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_CHATS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_COMMENTS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_CHATS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_COMMENTS,
	firestorePathSettingsGeneral,
	FIRESTORE_USER_SETTINGS_GENERAL_DISPLAY_NAME,
	FIRESTORE_USER_SETTINGS_GENERAL_LANGUAGES,
	FIRESTORE_USER_SETTINGS_GENERAL_USER_AVATAR,
	DATABASE_STATUS_ONLINE,
	DATABASE_STATUS_ONLINE_LAST,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_FACEBOOK,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_TWITCH,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_YOUTUBE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PRICE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DESCR,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_ORDERS,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_DOTA2,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_PUBG,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_LOL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_APEX,
	FIRESTORE_SELLER_SETTINGS_PROFILE_SERVICES_FORTNITE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_IMAGE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_YOUTUBE,
	fireStorePathSellerSettingProfile,
	storagePathSellerCarousel,
	storagePathSellerAvatar,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_AVATAR,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER_FEMALE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_DISPLAY_NAME,
	FIRESTORE_USER_SELLER_FAVOURITE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_VERIFIED,
	fireStorePathUser_Seller,
}
