const STORAGE_USER_AVATAR = 'userAvatar'

const storagePathUserAvatar = uid => {
	return `${STORAGE_USER_AVATAR}/${uid}.jpg`
}

const CREATED_AT = 'createdAt'
const UPDATED_AT = 'updatedAt'

const FIRESTORE_USER = 'users/'
const FIRESTORE_USER_SETTINGS = 'settings/'

const fireStorePathUserSettingsNotification = uid => {
	return FIRESTORE_USER + uid + '/' + FIRESTORE_USER_SETTINGS + 'notifications'
}

const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL = 'email'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES = 'orderUpdates'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER = 'newsletter'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_CHATS = 'chats'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_COMMENTS = 'comments'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH = 'push'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES = 'orderUpdates'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_CHATS = 'chats'
const FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_COMMENTS = 'comments'

const FIRESTORE_USER_SELLER_FAVOURITE = 'favourite'

const fireStorePathUserSenshi = (uid, senshiUid) => {
	return FIRESTORE_USER + uid + '/' + FIRESTORE_SENSHI + senshiUid
}

const firestorePathSettingsGeneral = uid => {
	return FIRESTORE_USER + uid + '/' + FIRESTORE_USER_SETTINGS + 'general'
}

const FIRESTORE_USER_SETTINGS_GENERAL_DISPLAY_NAME = 'displayName'
const FIRESTORE_USER_SETTINGS_GENERAL_LANGUAGES = 'languages'
const FIRESTORE_USER_SETTINGS_GENERAL_USER_AVATAR = STORAGE_USER_AVATAR

const FIRESTORE_SENSHI = 'senshi/'
const STORAGE_SELLER_AVATAR = 'senshiAvatar'
const STORAGE_SELLER_CAROUSEL = 'senshiCarousel'

const storagePathSenshiAvatar = uid => {
	return `${STORAGE_SELLER_AVATAR}/${uid}.jpg`
}

const storagePathSenshiCarousel = uid => {
	return `${STORAGE_SELLER_CAROUSEL}/${uid}.jpg`
}

const fireStorePathSenshiSettingProfile = uid => {
	return FIRESTORE_SENSHI + uid + '/' + FIRESTORE_USER_SETTINGS + 'profile'
}

const DATABASE_STATUS_ONLINE = 'online'
const DATABASE_STATUS_ONLINE_LAST = 'onlineLast'

const FIRESTORE_SELLER_SETTINGS_PROFILE_AVATAR = STORAGE_SELLER_AVATAR

const FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER = 'gender'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER_FEMALE = 'female'

const FIRESTORE_SELLER_SETTINGS_PROFILE_DISPLAY_NAME = 'displayName'

const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS = 'channels'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_FACEBOOK = 'facebook'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_TWITCH = 'twitch'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_YOUTUBE = 'youtube'

const FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_DOTA2 = 'Dota2'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_PUBG = 'PUBG'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_LOL = 'LOL'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_APEX = 'Apex'
const FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_FORTNITE = 'Fortnite'

const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL = 'carousel'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_IMAGE = 'image'
const FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_YOUTUBE = 'youtube'

export {
	CREATED_AT,
	UPDATED_AT,
	storagePathUserAvatar,
	STORAGE_USER_AVATAR,
	FIRESTORE_USER,
	FIRESTORE_USER_SETTINGS,
	fireStorePathUserSettingsNotification,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_ORDER_UPDATES,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_NEWS_LETTER,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_CHATS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_EMAIL_COMMENTS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_ORDER_UPDATES,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_CHATS,
	FIRESTORE_USER_SETTINGS_NOTIFICATION_PUSH_COMMENTS,
	firestorePathSettingsGeneral,
	FIRESTORE_USER_SETTINGS_GENERAL_DISPLAY_NAME,
	FIRESTORE_USER_SETTINGS_GENERAL_LANGUAGES,
	FIRESTORE_USER_SETTINGS_GENERAL_USER_AVATAR,
	DATABASE_STATUS_ONLINE,
	DATABASE_STATUS_ONLINE_LAST,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_FACEBOOK,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_TWITCH,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS_YOUTUBE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_DOTA2,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_PUBG,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_LOL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_APEX,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GAMES_FORTNITE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_IMAGE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL_YOUTUBE,
	fireStorePathSenshiSettingProfile,
	storagePathSenshiCarousel,
	storagePathSenshiAvatar,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CHANNELS,
	FIRESTORE_SELLER_SETTINGS_PROFILE_CAROUSEL,
	FIRESTORE_SELLER_SETTINGS_PROFILE_AVATAR,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER,
	FIRESTORE_SELLER_SETTINGS_PROFILE_GENDER_FEMALE,
	FIRESTORE_SELLER_SETTINGS_PROFILE_DISPLAY_NAME,
	FIRESTORE_USER_SELLER_FAVOURITE,
	fireStorePathUserSenshi,
}
