const FUNCTION_DATA = 'data'
const FUNCTION_STATUS = 'status'
const FUNCTION_CODE = 'code'
const FUNCTION_MESSAGE = 'message'
const FUNCTION_INPUT = 'Input'
const FUNCTION_EMAIL = 'email'
const FUNCTION_PASSWORD = 'password'
const FUNCTION_DISPLAY_NAME = 'displayName'
const FUNCTION_OAUTH_CODE = 'oAuthCode'
const FUNCTION_TOKEN_CUSTOM = 'customToken'
const FUNCTION_REDIRECT_URI = 'redirectUri'
const FUNCTION_UID = 'uid'
const FUNCTION_ON_DATA_SEED = 'onDataSeed'
const FUNCTION_ON_TWITCH_SIGN_IN = 'onTwitchSignIn'

export {
	FUNCTION_DATA,
	FUNCTION_STATUS,
	FUNCTION_CODE,
	FUNCTION_MESSAGE,
	FUNCTION_INPUT,
	FUNCTION_EMAIL,
	FUNCTION_PASSWORD,
	FUNCTION_DISPLAY_NAME,
	FUNCTION_OAUTH_CODE,
	FUNCTION_TOKEN_CUSTOM,
	FUNCTION_REDIRECT_URI,
	FUNCTION_ON_DATA_SEED,
	FUNCTION_ON_TWITCH_SIGN_IN,
	FUNCTION_UID,
}
